
type User {
    id: ID
    name: String
    password: String
}

input OneUser{
    name: String
    password: String
}

type Query {
    user(name: String!): User
    checkUserExist(name: String!): Boolean 
    checkUserPass(name: String!, password: String!): Boolean
}

type Mutation{
    addUser(input: OneUser): Boolean
    updateUser(name: String!, input: OneUser): Boolean
}
